name: myapp # Atau nama proyek Anda yang sebenarnya
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.1.beta # Anda menggunakan versi beta Dart SDK

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.7.0 
  flutter_bloc: ^8.1.6 
  equatable: ^2.0.5
  firebase_core: ^3.1.1 # Cek versi terbaru di pub.dev

  # Pastikan baris ini ada dan tidak ada tanda '#' di depannya
  image_picker: ^1.1.2 # Anda bisa mengecek versi terbaru di pub.dev

  firebase_auth: ^5.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/recipes.json       # Pastikan path ini benar
    - assets/snapcook_logo.png  # Pastikan path ini benar
  #  - assets/images/          # Jika Anda memiliki folder images, Anda bisa mendaftarkan seluruh folder
  #  - assets/fonts/           # Contoh jika Anda punya folder font

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package